In [1]:
import pandas as pd
import numpy as np
import sklearn.feature_selection as sk1
import sklearn.linear_model as sk2
import sklearn.metrics as sk3

In [2]:
data = pd.read_csv('pima-indians-diabetes.data.csv')

In [3]:
print(data)
print(data.shape)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [4]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
data2 = data.to_numpy()

In [6]:
data2

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [7]:
datay = [i for i in data['Outcome']]

In [8]:
datay


[1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,


In [9]:
datax = np.delete(data2,8,1)

In [10]:
select = sk1.SelectKBest(score_func = sk1.f_classif, k = 3)
data3 = select.fit_transform(datax,datay)

In [11]:
data3.shape

(768, 3)

In [12]:
datax[0][select.get_support()]


array([148. ,  33.6,  50. ])

In [13]:
select = sk1.SelectKBest(score_func = sk1.f_classif, k = 4)
data4 = select.fit_transform(datax,datay)

In [14]:
data4.shape

(768, 4)

In [15]:
datax[0][select.get_support()]


array([  6. , 148. ,  33.6,  50. ])

In [31]:
model = sk2.LogisticRegression()

x = []

for i in data2:
    x.append([i[0],i[5]])
    
model.fit(x,datay)


ypred = model.predict(x)

print("precision: ", sk3.precision_score(datay,ypred),", recall: ", sk3.recall_score(datay,ypred), "F1 score: ", sk3.f1_score(datay,ypred) )

precision:  0.5933333333333334 , recall:  0.332089552238806 F1 score:  0.42583732057416274


In [32]:
model = sk2.LogisticRegression()

x = []

for i in data2:
    x.append([i[0],i[7]])
    
model.fit(x,datay)


ypred = model.predict(x)

print("precision: ", sk3.precision_score(datay,ypred),", recall: ", sk3.recall_score(datay,ypred), "F1 score: ", sk3.f1_score(datay,ypred) )

precision:  0.5371900826446281 , recall:  0.24253731343283583 F1 score:  0.33419023136246784


In [33]:
model = sk2.LogisticRegression()

x = []

for i in data2:
    x.append([i[2],i[4]])
    
model.fit(x,datay)


ypred = model.predict(x)

print("precision: ", sk3.precision_score(datay,ypred),", recall: ", sk3.recall_score(datay,ypred), "F1 score: ", sk3.f1_score(datay,ypred) )

precision:  0.56 , recall:  0.05223880597014925 F1 score:  0.0955631399317406


In [34]:
model = sk2.LogisticRegression()

x = []

for i in data2:
    x.append([i[4],i[3]])
    
model.fit(x,datay)



ypred = model.predict(x)

print("precision: ", sk3.precision_score(datay,ypred),", recall: ", sk3.recall_score(datay,ypred), "F1 score: ", sk3.f1_score(datay,ypred) )

precision:  0.6521739130434783 , recall:  0.055970149253731345 F1 score:  0.10309278350515465


In [20]:
select = sk1.SelectKBest(score_func = sk1.f_classif, k = 5)
data5 = select.fit_transform(datax,datay)

In [35]:
data5.shape

(768, 5)

In [22]:
datax[0][select.get_support()]

array([  6.   , 148.   ,  33.6  ,   0.627,  50.   ])

In [23]:
select.get_support()

array([ True,  True, False, False, False,  True,  True,  True])